MEXT = md
#DIR = /var/...
#PFAD = $(pfad)
#SRC = $(wildcard $(pfad)/*.$(MEXT))

BEAM1610=$(SRC:.md=.16zu10.beamer.vortrag.pdf)
BEAM169=$(SRC:.md=.16zu9.beamer.vortrag.pdf)
BEAM149=$(SRC:.md=.14zu9.beamer.vortrag.pdf)
BEAM54=$(SRC:.md=.5zu4.beamer.vortrag.pdf)
BEAM43=$(SRC:.md=.4zu3.beamer.vortrag.pdf)
BEAM32=$(SRC:.md=.3zu2.beamer.vortrag.pdf)
BEAMTEX=$(SRC:.md=.beamer.vortrag.tex)
REVEALSIM=$(SRC:.md=.simple.reveal.vortrag.htm)
REVEALNIG=$(SRC:.md=.night.reveal.vortrag.htm)
HANDOUTPDF=$(SRC:.md=.handout.vortrag.pdf)
HANDOUTODT=$(SRC:.md=.handout.vortrag.odt)
TAR=$(SRC:.md=.paket.tar.gz)

all:  $(BEAM1610) $(BEAM169) $(BEAM149) $(BEAM54) $(BEAM43) $(BEAM32) $(BEAMTEX) $(HANDOUTPDF) $(HANDOUTODT) $(REVEALSIM) $(REVEALNIG) $(TAR)

beamer: clean-beamer $(BEAM1610) $(BEAM169) $(BEAM149) $(BEAM54) $(BEAM43) $(BEAM32) $(BEAMTEX)
reveal: clean-reveal $(REVEALSIM) $(REVEALNIG)
handout: clean-handout $(HANDOUTPDF) $(HANDOUTODT)
tar: clean-tar $(TAR)

%.16zu10.beamer.vortrag.pdf:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	-V aspectratio=1610 \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -o $@ $<

%.16zu9.beamer.vortrag.pdf:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	-V aspectratio=169 \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -o $@ $<

%.14zu9.beamer.vortrag.pdf:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	-V aspectratio=149 \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -o $@ $<

%.5zu4.beamer.vortrag.pdf:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	-V aspectratio=54 \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -o $@ $<

%.4zu3.beamer.vortrag.pdf:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	-V aspectratio=43 \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -o $@ $<

%.3zu2.beamer.vortrag.pdf:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	-V aspectratio=32 \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -o $@ $<

%.beamer.vortrag.tex:	%.md
	$(DIR)/cabal/bin/pandoc \
	--latex-engine=xelatex \
	--template=beamertheme/vorlage-beamer.tex \
	--no-tex-ligatures \
	-f markdown -t beamer -s -o $@ $<

%.simple.reveal.vortrag.htm: %.md
	$(DIR)/cabal/bin/pandoc \
	--data-dir=$(DIR)/cabal/share/pandoc-1.12.4.2/data/ \
	-V theme=simple \
	-V transition=fade \
	-V revealjs-url=dinge-und-sachen/reveal.js \
	-s \
	-S \
	-f markdown -t revealjs -o $@ $<

%.night.reveal.vortrag.htm: %.md
	$(DIR)/cabal/bin/pandoc \
	--data-dir=$(DIR)/cabal/share/pandoc-1.12.4.2/data/ \
	-V theme=night \
	-V transition=fade \
	-V revealjs-url=dinge-und-sachen/reveal.js \
	-s \
	-S \
	-f markdown -t revealjs -o $@ $<

%.handout.vortrag.pdf: %.md
	$(DIR)/cabal/bin/pandoc \
	-V mainfont:'Frutiger Next LT W1G' \
	-V sansfont:'Frutiger Next LT W1G' \
	-V papersize:a4 \
	-V lang=ngerman \
	-V mainlang=german \
	-V classoption='DIV=9' \
	-V classoption='headinclude' \
	-V classoption='footexclude' \
	-V header-includes='\usepackage[absolute]{textpos}' \
	-V header-includes='\MakeOuterQuote{"}' \
	-V header-includes='\usepackage[german=quotes]{csquotes}' \
	-V documentclass=scrartcl \
	-V include-before='\end{textblock}' \
	-V include-before='\includegraphics[scale=0.9]{layout/logo-uni-rz-stud-it-regular}' \
	-V include-before='\begin{textblock}{4}(1.71,1.2)' \
	-V include-before='\setlength{\TPVertModule}{\TPHorizModule}' \
	-V include-before='\setlength{\TPHorizModule}{1cm}' \
	--latex-engine=xelatex \
	--no-tex-ligatures \
	--toc \
	--template=$(DIR)/layout/vorlage-tex-pdf.tex \
	-s \
	-o $@ $<

%.handout.vortrag.odt: %.md
	$(DIR)/cabal/bin/pandoc \
	-V lang=ngerman \
	-V mainlang=german \
	--toc \
	--data-dir=$(DIR)/cabal/share/pandoc-1.12.4.2/data/ \
	--reference-odt=$(DIR)/layout/reference-stud-it.odt \
	-s \
	-o $@ $<

%.paket.tar.gz: %.md
	if [ ! -d "$(PFAD)/dinge-und-sachen" ]; then cp -r "$(DIR)/dinge-und-sachen" "$(PFAD)"; fi
	cd $(PFAD) && tar czf $@ --exclude=ur-beamer.paket.tar.gz *


clean:
	rm -f *.beamer.vortrag.pdf *.beamer.vortrag.tex *.reveal.vortrag.htm *.handout.vortrag.odt *.handout.vortrag.pdf

clean-reveal:
	rm -f *.reveal.vortrag.htm

clean-beamer:
	rm -f *.beamer.vortrag.pdf *.beamer.vortrag.tex

clean-handout:
	rm -f *.handout.vortrag.odt *.handout.vortrag.pdf

